ALTER TABLE roles
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'superadmin',
    ADD COLUMN updated_by VARCHAR(255),
    ADD COLUMN deleted_by VARCHAR(255),
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE permissions
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'superadmin',
    ADD COLUMN updated_by VARCHAR(255),
    ADD COLUMN deleted_by VARCHAR(255),
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN deleted_at TIMESTAMP;

ALTER TABLE users
    ADD COLUMN created_by VARCHAR(255) DEFAULT 'superadmin',
    ADD COLUMN updated_by VARCHAR(255),
    ADD COLUMN deleted_by VARCHAR(255),
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN deleted_at TIMESTAMP;

